### ISSUE TITLE
How to propagate errors up to login screen?

### ISSUE THREAD

**Issue by KostiaHfcu** [fredrikburmester/expo-router-3-tab-example-with-auth#2]
I apologize if this is the wrong place which it may very well be, but I am trying to follow your code while learning.
I got the healthy path working, but what happens if I want to add activity indication during login and handle failure of login in errors at the login screen? In login.tsx shouldn't I be able to either observe context or catch errors to dismiss activity and display errors from the server?

**Comment by fredrikburmester** [comment]
Hi, did you solve your issue? @KostiaHfcu

**Comment by KostiaHfcu** [comment]
Yes, thank you. I am new to RN and propagation of values, but I figured it out .

**Comment by KostiaHfcu** [comment]
I added errors property to AuthProvider / AuthContext , setting it in AuthProvider if an error is caught
